title_primary: "魔泡树的光与影" # the bigger text
title_secondary: "Lights and Shadows" # the smaller text
keywords:

twitter: #username
rss: atom.xml
weibo: #username/id
instagram: #username
github: LeptusHe

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.
gitalk:
  clientID: Ov23liWBkDHnxftzyPvw
  clientSecret: c16c4433baadd63298870c894e5de48567786c06
  repo: LeptusHe.github.io
  githubID: LeptusHe
  adminUser:
  distractionFreeMode: false

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: dark #light # light/dark