name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Pandoc
        uses: nikeee/setup-pandoc@v1
      - name: Test Pandoc
        run: echo "# Test" | pandoc -t html
      - name: install typst
        uses: baptiste0928/cargo-install@v2
        with:
          crate: typst
          git: https://github.com/typst/typst
      #    tag: v0.4.1
      #    version: "0.4.1"
      - name: "setup python 3.x"
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: "link package"
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os

            def find_directory_and_file(directory, subdirectory, filename):
                for dir_path, dir_names, filenames in os.walk(directory):
                    if subdirectory in dir_names:
                        file_path = os.path.join(dir_path, subdirectory, filename)
                        if os.path.exists(file_path):
                            return file_path
                return None
          
            def run_typst_link():
                link_cmd = "typst-ts-cli package link --manifest {0}".format(file_path)
                print("succeed to run cmd: {0}".format(link_cmd))
                os.system(link_cmd)
          
            root_path = "/home/"
          
            os.system("curl https://sh.rustup.rs -sSf | sh")
            os.system("$HOME/.cargo/env")
            os.system("cargo install --git https://github.com/Myriad-Dreamin/typst.ts typst-ts-cli --tag v0.4.1 --version 0.4.1")

            file_path = find_directory_and_file(root_path, "variables", "typst.toml")
            if file_path is None:
                print("failed to find files")
            else:
                print("filed files in {0}".format(file_path))
                run_typst_link()

      #- name: find variables of typst
      #  uses: jeertmans/filesfinder@latest
      #  id: ff # Any id, to be used later to reference to files output
      #  with:
          # Only argument, a single string, to be passed as arguments to ff.
          # See `ff --help` for more help.
          # Default: "*"
      #    args: --dir "/home/" -R "variables/typst.toml"
      #- name: Print files
      #  run: |
      #   cd /
      #   echo "${{ steps.ff.outputs.files }}"
      #   find /home/ -type f -name "variables/typst.toml"
      - name: Checkout  
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
          lfs: true
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public